//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Destination
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Image { get; set; }

        public HttpPostedFileWrapper ImageFile { get; set; }

        public virtual Country Country { get; set; }
    }
}
